# Nome da aplicação
spring.application.name=voluntech-backend

#--------Config do banco local------#
spring.datasource.url=jdbc:postgresql://localhost:5432/db_voluntech
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true